### ISSUE TITLE
TODO before 1.0 release

### ISSUE THREAD

**Issue by mpizenberg** [mpizenberg/elm-test-rs#55]
Here is a list of things that should be nice to fix before a 1.0 release:

- [ ] Re-add the `install` subcommand (not sure if needed for 1.0, maybe wait for 1.1?).
- [x] Check licensing of everything, including vendored code. For rust code, all deps can either be Apache-2.0, BSD-3-Clause, CC0, ISC, MIT or MPL-2.0 which are all fine if we release under BSD-3-Clause. Licenses of elm vendored code are now provided in full.
- [x] Maybe add some end-to-end tests? not sure but at least one might be good for pull requests in CI. done in #81 
- [x] Complete the `json` report to make it equivalent to the one of `elm-test` we can add other reports if needed. Done in 0647683 and mpizenberg/elm-test-runner#5
- [x] Complete the `junit` report to make it compatible with the one of `elm-test`. Some additional fields might be easy to add and nice to have. Done in b8192ac and mpizenberg/elm-test-runner#6
- [x] Try triggering all the `unwrap` in the code and see if we can improve behavior and output there. We might want to introduce [anyhow](https://github.com/dtolnay/anyhow). see #57 
- [x] Redo the diagram with the updated names of things in the code architecture. Done in bb03fda
- [x] Vendor some of the dependencies code in [elm-test-runner](https://github.com/mpizenberg/elm-test-runner). Done in mpizenberg/elm-test-runner#7
- [x] See if possible to write an upgrade program to change duplicate descriptions. Or at least see if it's possible to get all duplicate at once -> maybe make a PR in elm-explorations/test. Follow elm-explorations/test#163
- [x] Try understand why elm-test adds a description prefix with the module name. Is it a commodity thing? See rtfeldman/node-test-runner#493
- [x] Add a `root` option to specify where the root `elm.json` is. Done in #56 
- [x] Check the timeouts for the dependency resolution http calls. Increased from 1s to 10s in f4fa0fa

**Comment by mpizenberg** [comment]
I'll defer the `install` subcommand and end-to-end tests for the time being.

**Comment by mpizenberg** [comment]
Here are some issues discovered by lydell
- [ ] `elm-test-rs init` overwrote my elm.json with 2 spaces indentation instead of 4 (Elm uses 4).
- [ ] It also changed the order (of dependencies). Seems to be a mismatch whether - or / is considered to sort first `elm/foo` vs `elm-community/foo`
- [ ] Another difference compared to node-test-runner: 0 tests (either 0 files, or 0 exposed Test values) is an error in node-test-runner, but not en elm-test-rs
- [ ] `elm-test-rs --root /nope` gives no error.
- [ ] `elm-test make` is missing in elm-test-rs

**Comment by mpizenberg** [comment]
Version 1.0.0 released :) #82
